M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu22.04.1} date 2025-08-06T09:14:11+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-06T09:14:11+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1380
%
G90
G05
T1
X5.4097Y-4.47
X6.3625Y-4.47
M30
